"use client"

import { useEffect, useState } from "react"
import { ChevronLeft, ChevronRight, Fullscreen, Lightbulb, Play, Sparkles, TrendingUp, Users, Zap } from "lucide-react"

const slides = [
  { eyebrow: "DreHomes Marketing Team · July 2026", title: "Less chasing. More creating.", body: "A connected creative operating system turns listing knowledge, agent personality, and local authority into consistent content that earns attention and trust.", icon: Sparkles, action: "Start the playbook" },
  { eyebrow: "Why systems matter", title: "Great creative work needs protected focus.", body: "Clear briefs, visible ownership, fast approvals, asset links, and one shared calendar remove the friction that steals time from the work only your team can do.", metrics: [["53%", "Knowledge-worker time can be consumed by organizational productivity taxes"], ["4.6×", "Teams with priority processes are more likely to be effective"], ["80%", "Low-performing teams report busywork from insufficient automation"]] },
  { eyebrow: "The DreHomes operating system", title: "One visible flow from idea to impact.", body: "Intake → brief → production → edit → approval → scheduled → published → learn → repurpose.", flow: ["Capture", "Create", "Approve", "Publish", "Learn"] },
  { eyebrow: "Role growth tracks", title: "Build specialists, not bottlenecks.", body: "Every role has a weekly practice, a quality rubric, a tool stack, and a measurable 30/60/90-day outcome.", cards: [["Content Strategist", "Research, briefs, pillars, reporting"], ["Video / Editor", "Hooks, vertical storytelling, retention edits"], ["Brand Lead", "Templates, consistency, quality review"], ["Social / Community", "Social SEO, response, distribution"], ["Operations", "Workflow, approvals, assets, automation QA"]] },
  { eyebrow: "Social best practices", title: "Property gets attention. Perspective builds trust.", body: "Use property, people, place, proof, and perspective as your five content pillars. Pair discovery formats with saveable education.", cards: [["Reach", "Short vertical video, compelling first 2 seconds, local keywords"], ["Trust", "Carousels, checklists, neighborhood explainers, proof"], ["Community", "Comments, local spotlights, questions, agent POV"]] },
  { eyebrow: "Q4 2026 forecast", title: "Test signals. Do not chase noise.", body: "Predictions are hypotheses with confidence levels—not facts. Review them monthly with DreHomes data.", cards: [["High confidence", "Format portfolios: Reels for discovery + carousels/documents for trust"], ["High confidence", "Social search + hyperlocal authority compound"], ["Medium confidence", "Human-reviewed AI editing becomes a speed advantage"], ["High confidence", "Agent POV and behind-the-scenes content beat listing-only feeds"]] },
  { eyebrow: "Agent growth platform", title: "Give every agent a creator’s toolkit.", body: "A Dre Agents hub provides trend briefs, searchable ideas, tutorials, approved templates, campaigns, and a personal studio—without forcing agents to invent everything from scratch.", icon: Users },
  { eyebrow: "Zoho + social sharing", title: "Make advocacy easy after consent.", body: "After an agent opts in and connects a channel, a verified Zoho event can queue approved content under guardrails: rate caps, expiry dates, duplicate prevention, review controls, and an emergency pause.", icon: Zap },
  { eyebrow: "Phase two", title: "Raw footage to social-ready video.", body: "Upload vertical footage. AI proposes hook/edit variants, captions, thumbnail and brand treatment. A human approves the final 9:16 export before download or sharing.", icon: Play },
  { eyebrow: "30 / 60 / 90", title: "Turn the plan into a habit.", body: "30: brand kit, roles, templates and weekly planning. 60: repeatable formats, asset library, approval SLA and automation pilots. 90: scale winners, repurpose, review capacity and publish a scorecard.", icon: TrendingUp },
  { eyebrow: "Team commitment", title: "One skill. One system. One idea.", body: "Choose one skill to practice, one workflow to simplify, and one content idea to test this week. Measure what matters: saves, watch time, qualified conversations, production cycle time, and creative energy.", icon: Lightbulb },
]

export function PresentationDeck() {
  const [index, setIndex] = useState(0)
  const slide = slides[index]
  const Icon = slide.icon || Sparkles
  const move = (direction: number) => setIndex((current) => Math.max(0, Math.min(slides.length - 1, current + direction)))
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "ArrowRight" || event.key === " ") move(1); if (event.key === "ArrowLeft") move(-1); if (event.key === "Home") setIndex(0); if (event.key === "End") setIndex(slides.length - 1) }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey) }, [])
  const fullscreen = () => document.documentElement.requestFullscreen?.()
  return <main className="min-h-screen overflow-hidden bg-[#07111f] text-white"><div className="mx-auto flex min-h-screen max-w-7xl flex-col px-6 py-8 md:px-12"><header className="flex items-center justify-between text-xs uppercase tracking-[.2em] text-white/50"><span>DreHomes / Marketing Playbook</span><span>{String(index + 1).padStart(2, "0")} / {String(slides.length).padStart(2, "0")}</span></header><div className="mt-8 h-1 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#D4AF37] transition-all" style={{ width: `${((index + 1) / slides.length) * 100}%` }} /></div><section className="flex flex-1 flex-col justify-center py-12"><div className="grid gap-10 lg:grid-cols-[1.25fr_.75fr] lg:items-center"><div><p className="text-xs uppercase tracking-[.24em] text-[#D4AF37]">{slide.eyebrow}</p><h1 className="mt-5 max-w-4xl text-4xl font-bold leading-tight md:text-6xl">{slide.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">{slide.body}</p>{slide.flow && <div className="mt-8 flex flex-wrap gap-3">{slide.flow.map((part) => <span key={part} className="rounded-full border border-[#D4AF37]/40 bg-[#D4AF37]/10 px-4 py-2 text-sm">{part}</span>)}</div>}{slide.cards && <div className="mt-8 grid gap-3 sm:grid-cols-2">{slide.cards.map(([title, body]) => <div key={title} className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="font-semibold text-[#D4AF37]">{title}</p><p className="mt-1 text-sm text-white/65">{body}</p></div>)}</div>}{slide.metrics && <div className="mt-8 grid gap-3 sm:grid-cols-3">{slide.metrics.map(([metric, body]) => <div key={metric} className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-3xl font-bold text-[#D4AF37]">{metric}</p><p className="mt-2 text-xs text-white/60">{body}</p></div>)}</div>}</div><div className="grid aspect-square place-items-center rounded-[2.5rem] border border-white/10 bg-gradient-to-br from-[#D4AF37]/20 via-white/5 to-transparent"><Icon className="h-28 w-28 text-[#D4AF37]" strokeWidth={1} /></div></div></section><footer className="flex items-center justify-between"><button onClick={() => move(-1)} disabled={!index} className="inline-flex items-center gap-2 text-sm text-white/70 disabled:opacity-30"><ChevronLeft /> Previous</button><div className="flex gap-2">{slides.map((_, position) => <button key={position} aria-label={`Go to slide ${position + 1}`} onClick={() => setIndex(position)} className={`h-2 w-2 rounded-full ${position === index ? "bg-[#D4AF37]" : "bg-white/25"}`} />)}</div><div className="flex gap-3"><button onClick={fullscreen} className="text-white/60"><Fullscreen className="h-5 w-5" /></button><button onClick={() => move(1)} disabled={index === slides.length - 1} className="inline-flex items-center gap-2 text-sm font-semibold text-[#D4AF37] disabled:opacity-30">Next <ChevronRight /></button></div></footer></div></main>
}
